services:
  - type: web
    name: news54-web
    env: python
    plan: free
    buildCommand: pip install -r News54_online_v2/requirements.txt && python News54_online_v2/manage.py collectstatic --noinput
    startCommand: gunicorn news_aggregator.wsgi:application --chdir News54_online_v2 --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false

databases:
  - name: news54-db
    plan: free
