# Generated by Django 5.2.12 on 2026-03-25 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Источник')),
                ('base_url', models.URLField(verbose_name='Сайт')),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('html', 'HTML')], default='rss', max_length=10, verbose_name='Тип')),
                ('rss_url', models.URLField(blank=True, verbose_name='RSS URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('item_selector', models.CharField(blank=True, max_length=255)),
                ('title_selector', models.CharField(blank=True, max_length=255)),
                ('link_selector', models.CharField(blank=True, max_length=255)),
                ('summary_selector', models.CharField(blank=True, max_length=255)),
                ('date_selector', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=520, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('original_url', models.URLField(unique=True, verbose_name='Ссылка на оригинал')),
                ('image_url', models.URLField(blank=True, verbose_name='Изображение')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_news', to=settings.AUTH_USER_MODEL, verbose_name='Добавил вручную')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='news.category', verbose_name='Категория')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='news.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='news.news')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'unique_together': {('user', 'news')},
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_at'], name='news_news_publish_ad4867_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='news_news_slug_915ecd_idx'),
        ),
    ]
